[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
elgan-math = { git = "https://github.com/elgan65536/elgan-math" }
rand = "0.8.5"
rayon = "1.6.0"